version: "3.0"
services:
  mongo:
    image: 'mongo:4.2'
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - /data/mongodb/conf/mongod.conf:/etc/mongod.conf.orig
      - /data/mongodb/data:/data/db
      - /etc/localtime:/etc/localtime
    command: mongod --config /etc/mongod.conf.orig
