version: "3.0"
services:
  v2raya:
    image: mzz2017/v2raya
    container_name: v2raya
    ports:
      - 2017:2017
    privileged: true
    volumes:
      - "/lib/modules:/lib/modules:ro"
      - "/etc/resolv.conf:/etc/resolv.conf"
      - "/etc/v2raya:/etc/v2raya"            
    environment:
      - "V2RAYA_LOG_FILE=/tmp/v2raya.log"
    restart: always
#     network_mode: "host"
